{-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-}
module EvenFiboTest(tests) where

import Test.Framework.Providers.HUnit
import Test.HUnit

import qualified EulerHs.EvenFibo as EvenFibo -- 実装対象

tests =
  [ fiboTest
  , evenFiboSumTest
  ]

fiboTest = testCase "First 10 Terms" $
             assertEqual "1から89" expected actual
               where
                 expected = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
                 actual   = map EvenFibo.fibo [1..10]

evenFiboSumTest = testCase "400万より小さい偶数のフィボナッチ数の和" $
                    assertEqual "till 4M" expected actual
                      where
                        expected = 4613732
                        actual = sum . filter even $ EvenFibo.fiboListBelow 4000000
